// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Weeb(id int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch id {
		case 1:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div onload=\"notWeebAud.play()\" hx-on:click=\"notWeebAud.play()\" class=\" my-[30rem] flex flex-row m-4 p-2  w-full justify-center text-[5rem]\">JP is not a weeb.</div><audio id=\"notWeebAud\" autoplay once><source src=\"/public/assets/sounds/notWeeb.mp3\" type=\"audio/mpeg\"> This HTML5 player is not supported by your browser</audio>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case 2:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex flex-row m-4 p-2  my-[30rem] w-full justify-center text-[5rem]\">JP is a little bit of a weeb.</div><audio id=\"littleWeebAud\" once autoplay><source src=\"/public/assets/sounds/littleWeeb.mp3\" type=\"audio/mpeg\"> This HTML5 player is not supported by your browser</audio>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case 3:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"flex flex-row m-4 p-2 my-[30rem] w-full justify-center text-[5rem]\">JP is a weeb.</div><audio id=\"weebAud\" once autoplay><source src=\"/public/assets/sounds/weeb.mp3\" type=\"audio/mpeg\"> This HTML5 player is not supported by your browser</audio>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case 4:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex flex-row m-4 p-2 my-[30rem] w-full justify-center text-[5rem]\">JP is a massive weeb.</div><audio id=\"massWeebAud\" once autoplay><source src=\"/public/assets/sounds/massWeeb.mp3\" type=\"audio/mpeg\"> This HTML5 player is not supported by your browser</audio>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"flex flex-row m-4 p-2 my-[30rem] w-full justify-center text-[5rem]\">JP is a massive fucking weeb.</div><audio id=\"massFFWeebAud\" once autoplay><source src=\"/public/assets/sounds/massFFWeeb.mp3\" type=\"audio/mpeg\"> This HTML5 player is not supported by your browser</audio>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
